language: java
notifications:
  hipchat:
    rooms:
      secure: XbA2Jh4yD9S6Kw1clA2u25iGFB+aYdONCKM2+l5tpa6HJbbCjSsa0MUaPSgQLGwosVCA4v2VdmW1AnU6K8OQFgIbSjUDl8GfocYXcadE4/LelY2E0kTw/VxG6V1QMOUThA3obS/1DwTDg8nVGzdTlwM4wHxXPADAk2+8GMhxH8E=
deploy:
  provider: releases
  api_key:
    secure: JMWVFqrFUK5ct80EZNHKCfLhBsW28Nuxmn/QTIwEIUamvlA5xj8ndMzxwhDNAM4q989pab7rlcsM3Tc9oc+oBKoJ5TUvFGWmZy3R8H9mNcEIuszdianbyQehZzUNzTI/vB3ZQY0YbOSWjxv6I5TjHrx9B1X2HfnLvsiU/aIT2AI=
  file: build/libs/xld-tibcobw-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

