language: java
notifications:
  hipchat:
    rooms:
      secure: XbA2Jh4yD9S6Kw1clA2u25iGFB+aYdONCKM2+l5tpa6HJbbCjSsa0MUaPSgQLGwosVCA4v2VdmW1AnU6K8OQFgIbSjUDl8GfocYXcadE4/LelY2E0kTw/VxG6V1QMOUThA3obS/1DwTDg8nVGzdTlwM4wHxXPADAk2+8GMhxH8E=
deploy:
  provider: releases
  api_key:
    secure: irITEmV4StR21wzupRQGDHgC7E2rdECOnrxkCdcuPSjBgLhwxJWb8hskGzyTcpOkk2u3ldlQUAkG8JxvEiHbcOaV4z/yOwYtSptD49F9dLkZKoqNHr63IvuLgyfy0v+AEFxqiLKh/8IwdrK5pTNpfmsdZIWtd39O9tKWPBISbew=
  file: build/libs/xld-tibcobw-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-tibcobw-plugin
